DEFAULT:
  SHAPE: 'Diamond'
#  SHAPE: 'Triangle'
  SIZE: !!python/int 4
#  HOLES: [[1,2], [3,0]]
  HOLES: [[1, 2]]
  EPSILON: !!python/float 1.0
  EPSILON_DR: !!python/float 0.99
  AGENT_TYPE: 'Neural'
#  AGENT_TYPE: 'Table'
  EPISODES: !!python/int 600


TABLE:
  LEARNING_RATE: !!python/float 0.1
  ADDITIONAL_LEARNING: !!python/float 0.0
  DISCOUNT: !!python/float 0.9
  DECAY: !!python/float 0.1
  HIDDEN_LAYERS: []


NEURAL:
  LEARNING_RATE: !!python/float 0.1
  ADDITIONAL_LEARNING: !!python/float 0.05
  DISCOUNT: !!python/float 0.9
  DECAY: !!python/float 0.1
  HIDDEN_LAYERS: [64]




